// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type IdentityDocument string

const (
	IdentityDocumentIDENTITYDOCUMENTNATIONALID    IdentityDocument = "IDENTITY_DOCUMENT_NATIONAL_ID"
	IdentityDocumentIDENTITYDOCUMENTPASSPORT      IdentityDocument = "IDENTITY_DOCUMENT_PASSPORT"
	IdentityDocumentIDENTITYDOCUMENTDRIVERLICENSE IdentityDocument = "IDENTITY_DOCUMENT_DRIVER_LICENSE"
)

func (e *IdentityDocument) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdentityDocument(s)
	case string:
		*e = IdentityDocument(s)
	default:
		return fmt.Errorf("unsupported scan type for IdentityDocument: %T", src)
	}
	return nil
}

type NullIdentityDocument struct {
	IdentityDocument IdentityDocument `json:"identity_document"`
	Valid            bool             `json:"valid"` // Valid is true if IdentityDocument is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdentityDocument) Scan(value interface{}) error {
	if value == nil {
		ns.IdentityDocument, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdentityDocument.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdentityDocument) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdentityDocument), nil
}

type UserStatus string

const (
	UserStatusUSERSTATUSCREATED           UserStatus = "USER_STATUS_CREATED"
	UserStatusUSERSTATUSAPPROVALREQUESTED UserStatus = "USER_STATUS_APPROVAL_REQUESTED"
	UserStatusUSERSTATUSAPPROVED          UserStatus = "USER_STATUS_APPROVED"
	UserStatusUSERSTATUSREJECTED          UserStatus = "USER_STATUS_REJECTED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type User struct {
	ID               uuid.UUID        `json:"id"`
	Status           UserStatus       `json:"status"`
	Username         string           `json:"username"`
	PhoneNumber      string           `json:"phone_number"`
	PasswordHash     string           `json:"password_hash"`
	IdentityDocument IdentityDocument `json:"identity_document"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
}
