// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (status, username, phone_number, password_hash, identity_document)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, status, username, phone_number, password_hash, identity_document, created_at, updated_at
`

type CreateUserParams struct {
	Status           UserStatus       `json:"status"`
	Username         string           `json:"username"`
	PhoneNumber      string           `json:"phone_number"`
	PasswordHash     string           `json:"password_hash"`
	IdentityDocument IdentityDocument `json:"identity_document"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Status,
		arg.Username,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.IdentityDocument,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.IdentityDocument,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, status, username, phone_number, password_hash, identity_document, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Username,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.IdentityDocument,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
